### ISSUE TITLE
Change TFRUtil to TFRecorder in Notebooks

### ISSUE THREAD

**Issue by jmarrietar** [google/tensorflow-recorder#18]
**Describe the bug**
Notebooks inside `samples` directory have `import tfrutil` both from https://github.com/google/tensorflow-recorder/blob/master/samples/Basic-TFRecorder-Usage.ipynb and https://github.com/google/tensorflow-recorder/blob/master/samples/Using-TFRecorder-with-Google-Cloud-Dataflow.ipynb

**To Reproduce**
1. Go to `samples` directory and try to run the imports.

**Expected behavior**
`import tfrecorder`

**Additional context**
Maybe because this notebooks are still in an early phase. Cheers,

**Comment by mbernico** [comment]
Created hotfix 18 to address this.
