### ISSUE TITLE
Misleading example in readme

### ISSUE THREAD

**Issue by srcolinas** [google/tensorflow-recorder#19]
**Describe the bug**

**To Reproduce**
1. pip install tfrecorder on a clean environment
2. Follow example in README.nd

**Expected behavior**
I do not know whether you had some expected behavior than is different from the code sniped provided, which is just a copy from the README.md in the repo.

```python
import pandas as pd
import tfrecorder

df = pd.read_csv(...)
df.tensorflow.to_tfr(output_dir='gs://my/bucket')
```

**Screenshots**

![image](https://user-images.githubusercontent.com/18264558/90786791-9edfea80-e2c9-11ea-8c6e-8e25c8c8193c.png)

**System (please complete the following information):**
 - OS: macOS 10.15.6
 - Python Version: 3.6
 - TensorFlow Version: 2.2 (the one that gets installed with tfrecorder)
 - TensorFlow Transform Version: 0.23 (the one that gets installed with tfrecorder)

**Additional context**
I actually checked the code because it did not make sense to me that you would modify the dataframe or pandas to make the library work. I would spect a single function that accepts dataframe, perhaps with some predefined column names. On the otherhand, probably the example is just incomplete.

**Comment by jmarrietar** [comment]
Hi @srcolinas  In the screenshot it seems that you forgot to import the library `import tfrecorder` .  tfrecorder uses https://pandas.pydata.org/pandas-docs/stable/development/extending.html to extends pandas functionality.

**Comment by srcolinas** [comment]
> Hi @srcolinas In the screenshot it seems that you forgot to import the library `import tfrecorder` . tfrecorder uses https://pandas.pydata.org/pandas-docs/stable/development/extending.html to extends pandas functionality.

Thanks! I was not familiar with the api extensions..
