### ISSUE TITLE
Improve Installation Process [setup.py file location]

### ISSUE THREAD

**Issue by mchrestkha** [google/tensorflow-recorder#21]
**Is your feature request related to a problem? Please describe.**
The most likely installation process for most users may result in the Dataflow runner not working as the setup.py file for the Dataflow workers will not be in the right place.

**Describe the solution you'd like**
Assume users will only pip install and not clone the repo.  Place the setup.py file into the main library folder and update setup.py location in beam_pipeline.py

**Describe alternatives you've considered**
Got it working after moving the setup.py file into the main python ..python3.7/sitepackages/ folder.

**Additional context**

**Comment by mbernico** [comment]
Thanks for the report, recreating this now.

**Comment by mbernico** [comment]
Successfully reproduced, digging into the issue.

**Comment by mbernico** [comment]
Issue is at beam_pipeline.py 98.  

  if runner == 'DataflowRunner':
    options_dict['setup_file'] = _get_setup_py_filepath()

Setup file isn't installed when TFRecorder is installed via pypi / whl (works with git)

**Comment by mbernico** [comment]
It looks like TFDV solves this problem by prompting the user to download the whl and supply it as a command line option, passing it to beam pipeline options as an extra package. This is 'less easy' than I'd like it to be but some variation of this is the best idea I have for a fix at this time.

**Comment by mbernico** [comment]
This should now be resolves in git @mchrestkha 

I'll push it to pypi in just a few minutes as well.
